name: DiscordConsole
version: '${project.version}'
main: de.tomino.discordconsole.DiscordConsole
api-version: 1.19
description: a plugin that lets you interact with minecraft server console
commands:

  toggleDC:
    description: enables the plugin
    permission: discordconsole.toggle
    aliases:
      - toggleDC
      - tDC
      - toggleDiscordConsole

  setLogChannel:
    description: sets the log channel
    permission: discordconsole.setpreferences
    aliases:
      - setLogChannel
      - setLog

  setToken:
    description: sets the token
    permission: discordconsole.setpreferences
    aliases:
      - setToken
      - setBotToken

